<?php
/*
* 
*/

function form_fun_menu(){
    $items=array();
    $items['form_fun/cake'] = array(
        'title'=>'Cake or pie',
        'page callback' => 'form_fun_cake_page',
        'access arguments'=> array('access content'),
        'file' => 'form_fun_cake.inc',
        'weight'=>1,
    );
    $items['form_fun/tree'] = array(
        'title'=>'Im lost',
        'page callback' => 'drupal_get_form',
        'page arguments'=> array('form_fun_tree'),
        'access arguments'=> array('access content'),
        'file' => 'form_fun_tree.inc',
        'weight'=>3,
    );
    $items['form_fun/states'] = array(
        'title'=>'Partners',
        'page callback' => 'drupal_get_form',
        'page arguments'=> array('form_fun_blam_form'),
        'access arguments'=> array('access content'),
        'file' => 'form_fun.blam.inc',
        'weight'=>4,
    );
    return $items;
}